# -*- coding: utf-8 -*-
"""charger_3.9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mvey4u0wPIk4ds1frf6DnRnit6VrXe12
"""

import numpy as np
from scipy import fft, signal
from matplotlib import pyplot as plt
import os

ts = 1e-2
sig = np.zeros(200)
sig[:100] = 1
sig_fft = fft.fftshift(fft.fft(sig))
sig_fft = np.abs(sig_fft)/max(np.abs(sig_fft))
sf = fft.fftshift(fft.fftfreq(sig.size, d=ts))
plt.plot(sf, sig_fft, '.')
plt.plot(sf, np.sinc(sf))
plt.legend(['Simulation', 'Analysis'])
plt.grid()
plt.xlabel('f (Hz)')
plt.ylabel('H(f)')